# Generated by Django 5.2.6 on 2025-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('deal_id', models.CharField(max_length=100)),
                ('crm_source', models.CharField(max_length=50)),
                ('sync_timestamp', models.DateTimeField(auto_now_add=True)),
                ('file_id', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['deal_id', 'crm_source'], name='syncdata_sy_deal_id_7c8f04_idx')],
            },
        ),
    ]
