# Generated by Django 5.2.6 on 2025-09-17 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='syncedfile',
            name='syncdata_sy_deal_id_7c8f04_idx',
        ),
        migrations.AddField(
            model_name='syncedfile',
            name='file_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syncedfile',
            name='file_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncedfile',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='syncedfile',
            index=models.Index(fields=['deal_id', 'crm_source', 'size'], name='syncdata_sy_deal_id_70046c_idx'),
        ),
    ]
